GET http://localhost:3000/categories
###

POST http://localhost:3000/categories
Content-Type: application/json
    
{
    "name":"red skull"
}
###


GET http://localhost:3000/products
Authorization: Bearer 1058824|yF9Vhc5nJSz0Fjw1hCgoYbsk9ITggbB6SENcDx9G
###


POST http://localhost:3000/products
Content-Type: application/json

{
    "name":"second product",
    "price":10,
    "categoryId" : "65c8fe21c42097d47b294622"
}
